### ISSUE TITLE
 Cannot read properties of undefined (reading 'rimraf')

### ISSUE THREAD

**Issue by kauaicreative** [tomatrow/sveltekit-adapter-wordpress-shortcode#1]
Getting the error, ` Cannot read properties of undefined (reading 'rimraf')` with latest 

I have made sure that rimraf is installed both globally and locally.  For some reason utils is undefined `async adapt({ utils }) {`

```
> Using @sveltejs/adapter-wordpress-shortcode
> Cannot read properties of undefined (reading 'rimraf')
    at adapt (file:///Users/sun/www/flowsciences/app/public/wp-content/plugins/flow-builder/app/node_modules/sveltekit-adapter-wordpress-shortcode/index.js:18:19)
    at adapt (file:///Users/sun/www/flowsciences/app/public/wp-content/plugins/flow-builder/app/node_modules/@sveltejs/kit/dist/chunks/index5.js:873:8)
    at file:///Users/sun/www/flowsciences/app/public/wp-content/plugins/flow-builder/app/node_modules/@sveltejs/kit/dist/cli.js:1062:11
```

**Comment by kauaicreative** [comment]
Changing `async adapt({ utils })` to `async adapt(utils)` gives access to rimraf but other functions are still missing. I assume this adaptor needs to be updated to the latest version of sveltekit. 

Also, wondering if this adaptor has this functionality on the roadmap https://github.com/sveltejs/kit/issues/3882

Thanks!

**Comment by tomatrow** [comment]
@kauaicreative I do indeed need to update for the latest version of svelte-kit. I think we could configure esbuild/vite options to output a singular file, maybe even embed css in js too. I'll need to take a look at it.

**Comment by kauaicreative** [comment]
Thanks @tomatrow I'll keep an eye on this.

**Comment by tomatrow** [comment]
Well, it's updated for the latest kit version. It seems that Rich pushed a single-file output mode to post 1.0.

**Comment by tomatrow** [comment]
Closing since the original issue is resolved
