### ISSUE TITLE
Error: writeStatic has been removed

### ISSUE THREAD

**Issue by elron** [tomatrow/sveltekit-adapter-wordpress-shortcode#2]
When I `npm run build` I get this error:

> Using @sveltejs/adapter-wordpress-shortcode
error during build:
Error: writeStatic has been removed. Please ensure you are using the latest version of @sveltejs/adapter-wordpress-shortcode

**Comment by tomatrow** [comment]
@elron Thanks for the issue. I'll get it to work again with the latest kit version. (or feel free to pr if it interests you)

**Comment by elron** [comment]
I did a PR now :)
Thanks

**Comment by tomatrow** [comment]
@elron Um, thanks for the pr, sorry about the wait
